## ***************************************************************************
## ***************************************************************************
## Copyright 2022 - 2023 (c) Analog Devices, Inc. All rights reserved.
##
## In this HDL repository, there are many different and unique modules, consisting
## of various HDL (Verilog or VHDL) components. The individual modules are
## developed independently, and may be accompanied by separate and unique license
## terms.
##
## The user should read each of these license terms, and understand the
## freedoms and responsibilities that he or she has by using this source/core.
##
## This core is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
## A PARTICULAR PURPOSE.
##
## Redistribution and use of source or resulting binaries, with or without modification
## of this file, are permitted under one of the following two license terms:
##
##   1. The GNU General Public License version 2 as published by the
##      Free Software Foundation, which can be found in the top level directory
##      of this repository (LICENSE_GPL2), and also online at:
##      <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
##
## OR
##
##   2. An ADI specific BSD license, which can be found in the top level directory
##      of this repository (LICENSE_ADIBSD), and also on-line at:
##      https://github.com/analogdevicesinc/hdl/blob/master/LICENSE_ADIBSD
##      This will allow to generate bit files and not release the source code,
##      as long as it attaches to an ADI device.
##
## ***************************************************************************
## ***************************************************************************

name: Guideline checker

on:
  pull_request:
    branches:
      - master
    paths:
      - 'library/**'
      - 'projects/**'

jobs:
  guideline_check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          # version range
          python-version: '3.x'
      - name: Checkout repository code
        uses: actions/checkout@v3
        # repository that retrieves all the changed files
      - name: Load get-changed-files repo
        uses: Ana06/get-changed-files@v2.2.0
        id: changed_files
        with:
          format: space-delimited
      - name: Print changed files
        run: |
          echo "::group::Click here to see the Changed files"
          echo "${{ steps.changed_files.outputs.all }}"
          echo "::endgroup::"
      - name: Executing Py script for guideline check
        id: execution
        # -p flag means that files will be specified with their relative path
        run: |
          python ./.github/scripts/check_guideline.py -p ${{ steps.changed_files.outputs.all }}
        shell: sh
